"use client";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { motion } from "framer-motion";

const faqs = [
  {
    question: "Who is Acad AI for?",
    answer: "Acad AI is designed for anyone looking to start or advance a career in technology. This includes students, career changers, and existing professionals who want to upskill or switch domains.",
  },
  {
    question: "How are the roadmaps created?",
    answer: "Our roadmaps are generated by analyzing data from thousands of job postings, course curricula, and expert opinions. We then use this data to build a comprehensive, logical learning path that is both relevant and up-to-date.",
  },
  {
    question: "Can I customize my roadmap?",
    answer: "Currently, our roadmaps are AI-generated for optimal learning. We are exploring customization features for the future that will allow you to tailor your learning path based on your specific goals and preferences.",
  },
  {
    question: "How comprehensive are the roadmaps?",
    answer: "Our roadmaps provide comprehensive coverage of each domain, including foundational concepts, advanced topics, specialized tools, and current industry best practices. You get the complete professional-level learning experience that was previously premium content.",
  },
  {
    question: "Is Acad AI really free?",
    answer: "Yes! Acad AI is completely free to use. You get access to our comprehensive roadmaps (previously premium content) across all domains without any cost or subscription required.",
  },
];

const FAQ = () => {
  return (
    <section id="faq" className="py-20 md:py-28 bg-card">
      <div className="container max-w-4xl mx-auto">
        <div className="text-center">
          <h2 className="font-headline text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Frequently Asked Questions
          </h2>
          <p className="mt-4 text-muted-foreground text-lg">
            Have questions? We have answers. If you can't find what you're looking for, feel free to contact us.
          </p>
        </div>
        <motion.div
          className="mt-12"
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left font-semibold text-lg hover:no-underline">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground text-base">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </motion.div>
      </div>
    </section>
  );
};

export default FAQ;
