"use client";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { motion } from "framer-motion";

const faqs = [
  {
    question: "Who is Acad AI for?",
    answer: "Acad AI is designed for anyone looking to start or advance a career in technology. This includes students, career changers, and existing professionals who want to upskill or switch domains.",
  },
  {
    question: "How are the roadmaps created?",
    answer: "Our roadmaps are generated by analyzing data from thousands of job postings, course curricula, and expert opinions. We then use this data to build a comprehensive, logical learning path that is both relevant and up-to-date.",
  },
  {
    question: "Can I customize my roadmap?",
    answer: "While the initial roadmap is AI-generated for optimal learning, our premium plan allows for a 'live self-updating' feature that adapts based on your progress and evolving industry trends. Direct manual customization is a feature we are exploring for the future.",
  },
  {
    question: "What's the difference between the free and premium roadmaps?",
    answer: "The free roadmap provides the core foundational concepts for a given domain, giving you a strong start. The premium roadmap is exhaustive, covering advanced topics, specialized tools, and provides a much deeper, more comprehensive learning experience.",
  },
  {
    question: "How does the 'live self-updating roadmap' work?",
    answer: "For premium users, our system continuously monitors the tech landscape. When a new, important technology or skill emerges for your chosen path, your roadmap is automatically updated to include it, ensuring you're always learning the most current and valuable skills.",
  },
];

const FAQ = () => {
  return (
    <section id="faq" className="py-20 md:py-28 bg-card">
      <div className="container max-w-4xl mx-auto">
        <div className="text-center">
          <h2 className="font-headline text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Frequently Asked Questions
          </h2>
          <p className="mt-4 text-muted-foreground text-lg">
            Have questions? We have answers. If you can't find what you're looking for, feel free to contact us.
          </p>
        </div>
        <motion.div
          className="mt-12"
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left font-semibold text-lg hover:no-underline">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground text-base">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </motion.div>
      </div>
    </section>
  );
};

export default FAQ;
